services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cassandra_app
    environment:
      - FILE_SERVER_URL=http://localhost:8080
      - SSH_PRIVATE_KEY_PATH=/app/ssh/id_ed25519
    volumes: # The app only needs the ssh key to list remote files
      - ./ssh:/app/ssh:ro
    networks:
      - cassandra-network
    command: ["uvicorn", "backend.app:app", "--host", "0.0.0.0", "--port", "8000"]
    restart: unless-stopped

  proxy:
    build:
      context: .
      dockerfile: proxy/Dockerfile
    container_name: cassandra_proxy
    ports:
      - "8080:80"
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./ssh:/app/ssh:ro # The entrypoint script needs the key and stations.yaml
    networks:
      - cassandra-network
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/fuse
    privileged: true
    restart: unless-stopped

  ui:
    build: .
    environment:
      - FILE_SERVER_URL=http://proxy
    working_dir: /app
    depends_on:
      - app
    ports:
      - "8501:8501"
    command:
      ["python", "-m", "streamlit", "run", "ui/streamlit_app.py",
       "--server.port", "8501", "--server.address", "0.0.0.0"]
    networks:
      - cassandra-network
    restart: unless-stopped

networks:
  cassandra-network:
    driver: bridge